### ISSUE TITLE
Possible Bug in Handling Initial Zoom setting

### ISSUE THREAD

**Issue by markolbert** [allenhwkim/angularjs-google-maps#185] opened 2015-04-27 03:52 UTC
I wrote up a fairly comprehensive issue/possible solution over on SO. You can read about it at http://stackoverflow.com/questions/29885345/ng-map-cannot-read-property-apply-of-undefined-when-setting-zoom-level.

Is this something that needs to be fixed? Or am I using the library wrong?

**Comment by allenhwkim** [comment] 2015-05-02 15:48
This fix is released with version 1.7.7. Please reopen this issue if the problem is persistent. Thanks for your patience.

I think you found the same issue as it in https://github.com/allenhwkim/angularjs-google-maps/issues/181.

**Closed** 2015-05-10 16:05 UTC
Labels: bug
