### ISSUE TITLE
Export ngmap as CommonJS-module

### ISSUE THREAD

**Issue by brunnurs** [allenhwkim/angularjs-google-maps#434] opened 2015-12-15 09:52 UTC
It would be great if we could include ngmap with the [CommonJS modularization-syntax](http://wiki.commonjs.org/wiki/Modules/1.1#Module_Context). Using your great piece of code, especially in combination with NPM, browserify and AngularJS, would be much simpler.

As an example, have a look at my angular app.js file:

```javascript
var app = angular.module('myProject', [
    'cgBusy',
    'ngFileSaver',
    'ngmap',
    require('angular-ui-router'),
    require('angular-animate'),
    require('angular-resource'),
    require('angular-ui-bootstrap'),
    require('ng-file-upload'),
    require('angular-smart-table'),
    require('angular-cookies'),
    require('angular-translate'),
    require('angular-dynamic-locale')
```

Most of my 3rd party dependencies (except of the first three) are referenced with the CommonJS `require` - keyword. With [browserify](http://browserify.org/), all I need to do is to execute `browserify app.js > bundle.js` and all dependencies (and even more important the transitive dependencies) are loaded from NPM in the specified version and bundled to one file. No need to add the files to my `index.html` manually or with additional tools like Grunt/Gulp. All we need to do is the standard angular initialization.

AFAIK, it is quite easy to implement it. Add an `index.js`- file with the following content to your repo (example is the angular-animate dependency):

```javascript
require('./angular-animate');
module.exports = 'ngAnimate';
```

It is also an investment into the future, as the  [module-concept ](http://www.infoq.com/news/2014/09/ecmascript6) will be an important part of ECMAScript 6.

Let me know if I can help u!

**Comment by allenhwkim** [comment] 2015-12-17 02:51
It seems a good idea, but I do not have experience with CommonJS modularization-syntax. 
As long as the changes does not bother the existing users, I am good with changes. Please send us a PR. I would appreciate it.

**Comment by allenhwkim** [comment] 2015-12-23 04:13
Closing. This will be implemented by PR

**Closed by allenhwkim** 2015-12-23 04:13 UTC

**Comment by brunnurs** [comment] 2015-12-23 12:12
I will send you a PR in january 2016!

**Comment by nkovacic** [comment] 2016-01-27 14:40
Added a PR with UMD support https://github.com/allenhwkim/angularjs-google-maps/pull/496.

**Comment by brunnurs** [comment] 2016-02-11 08:33
Thx @nkovacic. The UMD-support fixed my issue, it's working fine with browserify now (see #510)

**Comment by EnzoIntiso** [comment] 2017-05-15 15:57
Hi,
despite the issue is closed, they CommonJS support seems to be still missing.
I added a PR to provide it #801.
