### ISSUE TITLE
Map is not Loading after once it is loading partially not displaying full map.

### ISSUE THREAD

**Issue by krushnachandra** [allenhwkim/angularjs-google-maps#687] opened 2016-09-17 10:55 UTC
ng-map zoom="8" 
center="{{vm.TownshipBoundaryPoints[1]}}" 
map-type-id="TERRAIN" 
style="width:1200px;height:600px;"
                                shape name="polygon"
                                       path="{{vm.TownshipBoundaryPoints}}"
                                       geodesic="true"
                                       stroke-color="#FF0000"
                                       stroke-opacity="1.0"
                                       stroke-weight="2"
                                       fill-color="#FF0000"
                                       fill-opacity="0.35"
                                shape
                            ng-map
=================================================
 function _getTownshipBoundaryPointById(StateId,TownshipId) {
            debugger;
            townshipService.getTownshipBoundaryPointById(StateId,TownshipId).then(function (response) {
                var arr = [];
                response.data.forEach(function (element) {

                    var array = [];
                    array.push( element.Latitude,element.Longitude);
                    arr.push(array);
                });
                vm.TownshipBoundaryPoints=arr;
            }, function (error) {
            });
        }
==================================================
This is my code first part is how i am displaying in html
Second part is my method for getting all the points from service

I don't know how to update the view after getting the response from service. Is there a way to reload the map again.

Can any one help to How to implement properly Map.

**Comment by allenhwkim** [comment] 2016-09-25 03:13
Closing
1. Could you follow the question properly
2. Duplicate of https://github.com/allenhwkim/angularjs-google-maps/issues/82

**Closed by allenhwkim** 2016-09-25 03:13 UTC
