### ISSUE TITLE
unable to get map

### ISSUE THREAD

**Issue by calidion** [allenhwkim/angularjs-google-maps#567] opened 2016-04-10 20:59 UTC
it has been very frequently
ng map fail to get the map object.

**Comment by calidion** [comment] 2016-04-10 21:16
solved by the following code:

```js
      var getMap = false;
      var timer;
      getMap: function(cb) {
        function repeat() {
          NgMap.getMap().then(function(map) {
            if (!getMap) {
              getMap = true;
              cb(map);
              clearInterval(timer);
            }
          });
        }
        timer = setInterval(repeat, 1000);
      }
```

**Comment by allenhwkim** [comment] 2016-04-11 01:12
As you see here, it should find a map in 2 seconds. If not, it returns error.
If your network is good, and google map is downloaded 2 seconds are good enough, I think.

```

  var getMap = function(id) {
    id = typeof id === 'object' ? id.id : id;
    id = id || 0;

    var deferred = $q.defer();
    var timeout = 2000;

    function waitForMap(timeElapsed){
      if(mapControllers[id]){
        deferred.resolve(mapControllers[id].map);
      } else if (timeElapsed > timeout) {
        deferred.reject('could not find map');
      } else {
        $window.setTimeout( function(){
          waitForMap(timeElapsed+100);
        }, 100);
      }
    }
    waitForMap(0);

    return deferred.promise;
  };
```

**Comment by derkoe** [comment] 2016-06-23 11:18
Could be a duplicate of #614

**Comment by neolectron** [comment] 2016-10-09 21:44
i've got simmilar issues. 2seconds aren't enough...
i have other modules loading at the same time, it takes me some CPU.
if I add throttling, i've got this error 100% of the time.

**Comment by solidevolution** [comment] 2017-01-02 15:02
Same here, map breaks while slow network connections

**Comment by justus-alex** [comment] 2017-01-17 18:43
Hello, @allenhwkim.

> If your network is good, and google map is downloaded 2 seconds are good enough, I think.

.. and if it's not?
What's the point to impose 2 seconds timeout since you're using a promise anyway?

**Comment by tintin1343** [comment] 2017-02-01 19:09
Hi @allenhwkim : Is there a fix for this? 
Thanks!

**Comment by allenhwkim** [comment] 2017-03-04 21:05
@tintin1343 There should be a fix. It's just terribly busy. PR would be appreciated. Closing this as duplicate.

**Comment by allenhwkim** [comment] 2017-03-04 21:05
Duplicate to #614

**Closed by allenhwkim** 2017-03-04 21:05 UTC
