### ISSUE TITLE
Problem with method 'deleteObject' of MapController

### ISSUE THREAD

**Issue by akserg** [allenhwkim/angularjs-google-maps#169] opened 2015-04-01 17:22 UTC
Hi,

In our application we use **ui-router** to manage states between several **pages**. One page shows device location on **ng-map** (version 1.4.5) with **markers** and **shapes**. When I navigate out to other **page** the **MapController** runs with exception:

```
TypeError: Cannot read property 'markers' of null
    at deleteObject (ng-map.js:1507)
    at HTMLUnknownElement.<anonymous> (ng-map.js:1685)
    at HTMLUnknownElement.jQuery.event.dispatch (jquery.js:4430)
    at HTMLUnknownElement.jQuery.event.add.elemData.handle (jquery.js:4116)
    at Object.jQuery.event.trigger (jquery.js:4345)
    at jQuery.fn.extend.triggerHandler (jquery.js:4902)
    at Function.jQuery.cleanData (angular.js:1554)
    at jQuery.fn.extend.remove (jquery.js:5253)
    at Object.$AnimateProvider.$get.leave (angular.js:4685)
    at angular-animate.js:976 
```

This exception happens because code deletes a map firstly in `obj.setMap(null)` statement and later try to fetch objects from `null` object:

```
this.deleteObject = function(groupName, obj) {
    /* delete from map */
    obj.map && obj.setMap(null);          

    /* delete from group */
    var objs = obj.map[groupName];**
    for (var name in objs) {
      objs[name] === obj && (delete objs[name]);
    }
};
```

I didn't find unittests for this method, so my filling here tells me that solution might be very simple: just move first statement `obj.map && obj.setMap(null);` after `for` block and the issue will gone:

```
this.deleteObject = function(groupName, obj) {
    /* delete from group */
    var objs = obj.map[groupName];**
    for (var name in objs) {
      objs[name] === obj && (delete objs[name]);
    }

    /* delete from map */
    obj.map && obj.setMap(null);          
};
```

 I'm ready to make a pull request if that solution is correct from development perspective or you can do it yourself.

**Comment by allenhwkim** [comment] 2015-04-02 23:01
Sorry for the bug 

I will test it again and make a fix. My guess is map.markers is not set up properly or marker.map is not set.

**Comment by allenhwkim** [comment] 2015-04-03 02:04
Your are right, I made a fix with 1.4.7

**Comment by akserg** [comment] 2015-04-03 12:47
Thank you for prompt fix.

**Comment by jaiversin** [comment] 2015-04-17 02:54
I'm using Ionic Framework on a mobile app and I'm using the lazy loading attribute (under 1.7.7 version.) but I'm still having this messages the first time I open my view:

    Error: Can't find variable: google

I'm loading my view like this:
 
    <map  map-lazy-load="https://maps.google.com/maps/api/js"  center="{{position.lat}}, {{position.lng}}" street-view-control="false" zoom-control="false" map-type-control="false"> 
	  <marker ng-repeat="pos in positions" position="{{pos.officeLat}},{{pos.officeLng}}"></marker>
    </map> 
Then I'm having this Error when leaving the controller and going elsewhere on the app. After this, other sections stop working. 

    TypeError: undefined is not an object (evaluating 'obj.map[groupName]')

When debugging, the map object is undefined. Is there a way to mannually call the destroy process on the directives within the 'on destroy' event of the controller?

By now, I'm making validation as a work around:

    if (typeof obj !== 'undefined' && typeof obj.map !== 'undefined')
        obj.map[groupName]
 

I'm sorry if I'm missing some other configurations or obvious step!

**Comment by allenhwkim** [comment] 2015-04-18 14:24
can u create a plnkr for this? I have tested map-lazy-load and it worked fine, but not combined with ionic framework.

**Comment by jaiversin** [comment] 2015-04-22 20:17
Hi, sorry for the "lazy" response. I've made this very basic plnkr, only loading the AngulaJS/Ionic dependencies. But everything seems to work well on a web scenario. 

http://plnkr.co/edit/vULcuIAedgnd56Hpt88o?p=preview

I've implemented this on a mobile app and when the it initially loads with an internet connection, it works like a charm. The problem is when the app is loaded the first time with no internet connection and then it gains connection and tries to draw the Map directive again. The error message states for not finding the 'google' variable.

I hope you can help me with this!

**Comment by allenhwkim** [comment] 2015-04-24 19:14
`map-lazy-load` does not watch the internet connection. 
So, if your app is connected to internet again, the page has to load again.

**Comment by jaiversin** [comment] 2015-04-24 19:34
The internet connection check is made by the Cordova. I can't just reload the page, because in this case, the user is authenticated on the AngularJS $scope and I can't save any auth data on the device for automatic authentication.

Is there a way to reload the directive (including the lazy load of the Google Maps API), or maybe injecting the Map directive after the 'map-lazy-load' directive ends loading the Maps API?

Thanks again.

**Comment by allenhwkim** [comment] 2015-04-24 20:05
I don't know how to tackle this issue. Is this reproducible on browser by manually turning on and off the internet? If so, LMK, so that I can test it.

**Comment by allenhwkim** [comment] 2015-05-02 14:55
Closing this, @jaiversin please create another issue for `map-lazy-load` in mobile device.

**Closed** 2015-05-02 14:55 UTC
Labels: bug

**Comment by idrenski** [comment] 2016-03-31 06:54
I get an error angular.js:13424 TypeError: Cannot read property 'addObject' of null
    at linkFunc (http://localhost:63342/.../bower_components/ngmap/build/scripts/ng-map.js:1676:18)

Any idea how to workaround it?
