### ISSUE TITLE
map not loaded when usung ng show

### ISSUE THREAD

**Issue by warm200** [allenhwkim/angularjs-google-maps#368] opened 2015-11-09 17:22 UTC
Hi, there I just define a ng show variable to show a when click a button, but the map is not loaded , But I can see only the border of wapper div
<map ng-show="showmap" center="-25.363882, 131.044922" ></map>

**Comment by allenhwkim** [comment] 2015-11-09 18:04
Please provide me a plunker example

**Comment by allenhwkim** [comment] 2015-11-11 15:05
Closing. if you can reproduce issue with a plunker example, it will be reopened.

**Closed by allenhwkim** 2015-11-11 15:05 UTC
Labels: Waiting For Example

**Comment by celsomtrindade** [comment] 2015-11-19 23:58
I ran into the same problem. 

I've created a tab system using ng-show. When the map is in tab 2, for example and I start on tab 1, when i change to tab 2, the map only show as a grey screen. Only works normal when starting direct at tab 2.

See this plunkr: http://plnkr.co/edit/iJRAgrMpSsme1aKuOz4v?p=preview

Using `ng-if` instead of  `ng-show` works.

**Comment by allenhwkim** [comment] 2015-11-20 03:57
It's simple. 

Google maps were rendered within hidden element, which is 0px width and 0px height, and you are hiding and hiding those. `ng-if` works because it recreates the DOM element and rerender the map. 

You need to resize the map if you want to start it as hidden element.
