### ISSUE TITLE
Attributes of ng-map are not being evaluated 

### ISSUE THREAD

**Issue by harm-less** [allenhwkim/angularjs-google-maps#413] opened 2015-11-30 21:53 UTC
Im not sure if I'm correct, but it doesn't seem the zoom (and others?) is being evaluated properly if at all.
Next to the `ng-map` directive I'm using `zoom` and a few others. This is a dynamic value like this: `zoom="{{location.map.zoom != 0 ? location.map.zoom : 12}}"` but then a console error occurs: `InvalidValueError: setZoom: not a number`.

When I pause the code right before the options are being given to the GM API like this `vm.map.setOptions(mapOptions);` in the `initializeMap` method the object looks like this:
```javascript
apOptions: Object
center: _.K
defaultStyle: true
minZoom: 8
streetViewControl: false
styles: Array[19]
zoom: "{{location.map.zoom != 0 ? location.map.zoom : 12}}"
__proto__: Object
```
So it seems the attributes (at least the `zoom`) are not being evaluated but I think they should be, am I right about this?

**Comment by harm-less** [comment] 2015-12-01 12:57
I think the problem is bigger than the ng-maps only.

I've just noticed the panorama stopped working too when using dynamic values at certain places. I've made a Plunker to demonstrate: http://plnkr.co/edit/7IF7hYLfqH22VeyXuBV6?p=preview
I expect it to be the same as this demo: http://ngmap.github.io/#/street-view-panorama.html

In the console you'll get an `"InvalidValueError: setPov: not an Object"` error because it doesn't convert the attribute value into an object like I expect. But it does do this when using regular values like the http://ngmap.github.io/#/street-view-panorama.html demo.

**Comment by allenhwkim** [comment] 2015-12-04 00:35
Thanks for reporting this bug. It is not related to #354.
This happens because attribute is dynamically bound, and the value of the attribute is not parsed at the time of directive is initialized.

For example, 

  zoom accepts only integer, and "{{location.map.zoom != 0 ? location.map.zoom : 12}}" is not an integer even after went through Attr2MapOptions.

This should be parsed or eval'ed with scope before making use of it to prevent errors.

**Comment by harm-less** [comment] 2015-12-04 09:34
Hey Allen,

Alright, but I'm a bit confused by your last sentence though. Because is there something I can do to dynamically bound a value or is it something that needs to be added to the repository?

Anyway, I made a fix myself that seems to work for the purposes I at least need it for, I'm not sure if it's any good but see it for yourself at the pull-requests.

Harm

**Comment by allenhwkim** [comment] 2015-12-08 02:39
@harm-less thanks, you change has been released as 1.15.0

**Closed by allenhwkim** 2015-12-08 02:39 UTC
Labels: bug

**Comment by piotrd** [comment] 2015-12-08 16:34
I have just upgraded to version 1.15.1 and am experiencing this error. The stacktrace is as follows:

```
InvalidValueError: setZoom: not a number
_.bb @ js?callback=lazyLoadCallback:33
_.Eb @ js?callback=lazyLoadCallback:37
(anonymous function) @ js?callback=lazyLoadCallback:47
_.m.setValues @ js?callback=lazyLoadCallback:89
vm.initializeMap @ ng-map.js:173
__MapController @ ng-map.js:223
invoke @ angular.js:4219
extend.instance @ angular.js:8525
(anonymous function) @ angular.js:7771
forEach @ angular.js:334
nodeLinkFn @ angular.js:7770
compositeLinkFn @ angular.js:7149
publicLinkFn @ angular.js:7028
(anonymous function) @ ng-map.js:1311
(anonymous function) @ angular.js:16380
completeOutstandingRequest @ angular.js:4940
(anonymous function) @ angular.js:5328
```

Is it a regression or the issue hasn't been fixed entirely?

**Comment by allenhwkim** [comment] 2015-12-10 15:28
regression. We change all, but missed map tag. Trying to figure out not to miss this kind of bug next time.
