### ISSUE TITLE
'current-position' not working on windows firefox

### ISSUE THREAD

**Issue by minipolis** [allenhwkim/angularjs-google-maps#427] opened 2015-12-09 04:36 UTC
I have a problem getting the current location of the user, simply open the following example on windows 7 firefox and allow the location lookup, it will take you to  geo-fallback-center="[40.74, -74.18]"
https://ngmap.github.io/#/map_with_current_position.html

**Comment by minipolis** [comment] 2015-12-09 04:47
This is probably related (only happens in firefox), i have a problem when loading the map with 'current-position' as the center. It fails if the user accepts location lookup and also if he denies it. The problem is I cant read the current position value.

replicate:

Initialize map:
<div map-lazy-load id="map">
    <ng-map center='current-position'
            geo-fallback-center="[14.58, 121.05]"
            geo-callback="initLocation()">
 </ng-map>
</div>

2 functions to read the current location.

First one is if the map is ready and user denies access, when i try to read the map center location there is nothing.

NgMap.getMap().then(function(initializedMap) {
                    if(initializedMap.getCenter()){
                        scope.emitLocation();
                    }
                });

Second one is if user accepts location access, when the location is complete the callback function is never called.

 scope.initLocation = function(){
                    NgMap.getMap().then(function(initializedMap) {
                        focusMarker(initializedMap);
                        scope.emitLocation();
                    });
                };

**Comment by allenhwkim** [comment] 2015-12-13 15:53
It looks like a browser and OS issue. I don't know I can do something about it.
I will leave it as it is, and investigate it later when I have windows machine.

**Comment by david-lee** [comment] 2015-12-24 05:55
I think it might be related to only the specific environment. I've tested with Firefox 43.0.2 on Windows 8.1 Pro and worked fine.

**Comment by allenhwkim** [comment] 2015-12-25 13:13
THANKS @david-lee closing. It will be reopened when the same issue happens by other.

**Closed by allenhwkim** 2015-12-25 13:13 UTC

**Comment by danaronoff** [comment] 2016-05-31 02:02
I can confirm this is a problem for me too, but it is because Mozilla hasn't implemented Geolocation in a standards compliant way.

https://bugzilla.mozilla.org/show_bug.cgi?id=675533#c138

In Firefox, you must accept the geolocation request, or say "Never". Ignoring it or saying "Not Now" will cause an ngMap map to never load if relying on current-position for its center.
